# Generated by Django 5.1.7 on 2025-03-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskTracker', '0003_worker_address_worker_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
